export const hsr = 
[
  {
    id: '0',
    Name: 'Arlan',
    Path: 'Destruction',
    Element: 'Lightning',
    Version: '1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Herta Space Station',
    Height: 'Small',
    img: '../images/Hsr/Character_Arlan_Icon.webp'
  },
  {
    id: '1',
    Name: 'Asta',
    Path: 'Harmony',
    Element: 'Fire',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Herta Space Station',
    Height: 'Medium',
    img: '../images/Hsr/Character_Asta_Icon.webp'
  },
  {
    id: '2',
    Name: 'Bailu',
    Path: 'Abundance',
    Element: 'Lightning',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Vidyadhara',
    Worlds: 'The Xianshou Luofu',
    Height: 'Small',
    img: '../images/Hsr/Character_Bailu_Icon.webp'
  },
  {
    id: '3',
    Name: 'Bronya',
    Path: 'Harmony',
    Element: 'Wind',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Medium',
    img: '../images/Hsr/Character_Bronya_Icon.webp'
  },
  {
    id: '4',
    Name: 'Clara',
    Path: 'Destruction',
    Element: 'Physical',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Small',
    img: '../images/Hsr/Character_Clara_Icon.webp'
  },
  {
    id: '5',
    Name: 'Dan Heng',
    Path: 'The Hunt',
    Element: 'Wind',
    Version: '1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Vidyadhara',
    Worlds: 'Astral Express',
    Height: 'Medium',
    img: '../images/Hsr/Character_Dan_Heng_Icon.webp'
  },
  {
    id: '6',
    Name: 'Gepard',
    Path: 'Preservation',
    Element: 'Ice',
    Version: '1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Tall',
    img: '../images/Hsr/Character_Gepard_Icon.webp'
  },
  {
    id: '7',
    Name: 'Herta',
    Path: 'Erudition',
    Element: 'Ice',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Puppet',
    Worlds: 'Herta Space Station',
    Height: 'Small',
    img: '../images/Hsr/Character_Herta_Icon.webp'
  },
  {
    id: '8',
    Name: 'Himeko',
    Path: 'Erudition',
    Element: 'Fire',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Astral Express',
    Height: 'Tall',
    img: '../images/Hsr/Character_Himeko_Icon.webp'
  },
  {
    id: '9',
    Name: 'Hook',
    Path: 'Destruction',
    Element: 'Fire',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Small',
    img: '../images/Hsr/Character_Hook_Icon.webp'
  },
  {
    id: '10',
    Name: 'Jing Yuan',
    Path: 'Erudition',
    Element: 'Lightning',
    Version: '1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Tall',
    img: '../images/Hsr/Character_Jing_Yuan_Icon.webp'
  },
  {
    id: '11',
    Name: 'March 7th',
    Path: 'Preservation',
    Element: 'Ice',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Astral Express',
    Height: 'Medium',
    img: '../images/Hsr/Character_March_7th_Icon.webp'
  },
  {
    id: '12',
    Name: 'Natasha',
    Path: 'Abundance',
    Element: 'Physical',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Tall',
    img: '../images/Hsr/Character_Natasha_Icon.webp'
  },
  {
    id: '13',
    Name: 'Pela',
    Path: 'Harmony',
    Element: 'Ice',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Small',
    img: '../images/Hsr/Character_Pela_Icon.webp'
  },
  {
    id: '14',
    Name: 'Qingque',
    Path: 'Erudition',
    Element: 'Quantum',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Small',
    img: '../images/Hsr/Character_Qingque_Icon.webp'
  },
  {
    id: '15',
    Name: 'Sampo',
    Path: 'Nihility',
    Element: 'Wind',
    Version: '1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Tall',
    img: '../images/Hsr/Character_Sampo_Icon.webp'
  },
  {
    id: '16',
    Name: 'Seele',
    Path: 'The Hunt',
    Element: 'Quantum',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Medium',
    img: '../images/Hsr/Character_Seele_Icon.webp'
  },
  {
    id: '17',
    Name: 'Serval',
    Path: 'Erudition',
    Element: 'Lightning',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Tall',
    img: '../images/Hsr/Character_Serval_Icon.webp'
  },
  {
    id: '18',
    Name: 'Tingyun',
    Path: 'Harmony',
    Element: 'Lightning',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Foxian',
    Worlds: 'The Xianshou Luofu',
    Height: 'Medium',
    img: '../images/Hsr/Character_Tingyun_Icon.webp'
  },
  {
    id: '19',
    Name: 'Sushang',
    Path: 'The Hunt',
    Element: 'Physical',
    Version: '1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Medium',
    img: '../images/Hsr/Character_Sushang_Icon.webp'
  },
  {
    id: '20',
    Name: 'Trailblazer (Destruction)',
    Path: 'Destruction',
    Element: 'Physical',
    Version: '1',
    Gender: 'Both',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Artificial Body',
    Worlds: 'Astral Express',
    Height: 'Medium',
    img: '../images/Hsr/Character_Trailblazer_Icon.webp'
  },
  {
    id: '21',
    Name: 'Trailblazer (Preservation)',
    Path: 'Preservation',
    Element: 'Fire',
    Version: '1',
    Gender: 'Both',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Artificial Body',
    Worlds: 'Astral Express',
    Height: 'Medium',
    img: '../images/Hsr/Character_Trailblazer_P_Icon.webp'
  },
  {
    id: '22',
    Name: 'Welt',
    Path: 'Nihility',
    Element: 'Imaginary',
    Version: '1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Astral Express',
    Height: 'Tall',
    img: '../images/Hsr/Character_Welt_Icon.webp'
  },
  {
    id: '23',
    Name: 'Yanqing',
    Path: 'The Hunt',
    Element: 'Ice',
    Version: '1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Small',
    img: '../images/Hsr/Character_Yanqing_Icon.webp'
  },
  {
    id: '24',
    Name: 'Silver Wolf',
    Path: 'Nihility',
    Element: 'Quantum',
    Version: '1.1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Stellaron Hunter',
    Height: 'Small',
    img: '../images/Hsr/Character_Silver_Wolf_Icon.webp'
  },
  {
    id: '25',
    Name: 'Yukong',
    Path: 'Harmony',
    Element: 'Imaginary',
    Version: '1.1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Foxian',
    Worlds: 'The Xianshou Luofu',
    Height: 'Tall',
    img: '../images/Hsr/Character_Yukong_Icon.webp'
  },
  {
    id: '26',
    Name: 'Blade',
    Path: 'Destruction',
    Element: 'Wind',
    Version: '1.2',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Long-Life Species',
    Worlds: 'Stellaron Hunter',
    Height: 'Tall',
    img: '../images/Hsr/Character_Blade_Icon.webp'
  },
  {
    id: '27',
    Name: 'Kafka',
    Path: 'Nihility',
    Element: 'Lightning',
    Version: '1.2',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Stellaron Hunter',
    Height: 'Tall',
    img: '../images/Hsr/Character_Kafka_Icon.webp'
  },
  {
    id: '28',
    Name: 'Luka',
    Path: 'Nihility',
    Element: 'Physical',
    Version: '1.2',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Medium',
    img: '../images/Hsr/Character_Luka_Icon.webp'
  },
  {
    id: '29',
    Name: 'Dan Heng - Imbibitor Lunae',
    Path: 'Destruction',
    Element: 'Imaginary',
    Version: '1.3',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Vidyadhara',
    Worlds: 'Astral Express',
    Height: 'Medium',
    img: '../images/Hsr/Character_Dan_Heng_Imbibitor_Lunae_Icon.webp'
  },
  {
    id: '30',
    Name: 'Fu Xuan',
    Path: 'Preservation',
    Element: 'Quantum',
    Version: '1.3',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Small',
    img: '../images/Hsr/Character_Fu_Xuan_Icon.webp'
  },
  {
    id: '31',
    Name: 'Lynx',
    Path: 'Abundance',
    Element: 'Quantum',
    Version: '1.3',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Belobog',
    Height: 'Small',
    img: '../images/Hsr/Character_Lynx_Icon.webp'
  },
  {
    id: '32',
    Name: 'Guinaifen',
    Path: 'Nihility',
    Element: 'Fire',
    Version: '1.4',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Short-Live Species',
    Worlds: 'The Xianshou Luofu',
    Height: 'Medium',
    img: '../images/Hsr/Character_Guinaifen_Icon.webp'
  },
  {
    id: '33',
    Name: 'Jingliu',
    Path: 'Destruction',
    Element: 'Ice',
    Version: '1.4',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Medium',
    img: '../images/Hsr/Character_Jingliu_Icon.webp'
  },
  {
    id: '34',
    Name: 'Topaz',
    Path: 'The Hunt',
    Element: 'Fire',
    Version: '1.4',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Interastral Peace Corporation',
    Height: 'Medium',
    img: '../images/Hsr/Character_Topaz_Icon.webp'
  },
  {
    id: '35',
    Name: 'Argenti',
    Path: 'Erudition',
    Element: 'Physical',
    Version: '1.5',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Knights of Beauty',
    Height: 'Tall',
    img: '../images/Hsr/Character_Argenti_Icon.webp'
  },
  {
    id: '36',
    Name: 'Hanya',
    Path: 'Harmony',
    Element: 'Physical',
    Version: '1.5',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Tall',
    img: '../images/Hsr/Character_Hanya_Icon.webp'
  },
  {
    id: '37',
    Name: 'Huohuo',
    Path: 'Abundance',
    Element: 'Wind',
    Version: '1.5',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Foxian',
    Worlds: 'The Xianshou Luofu',
    Height: 'Small',
    img: '../images/Hsr/Character_Huohuo_Icon.webp'
  },
  {
    id: '38',
    Name: 'Dr. Ratio',
    Path: 'The Hunt',
    Element: 'Imaginary',
    Version: '1.6',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Herta Space Station',
    Height: 'Tall',
    img: '../images/Hsr/Character_Dr._Ratio_Icon.webp'
  },
  {
    id: '39',
    Name: 'Ruan Mei',
    Path: 'Harmony',
    Element: 'Ice',
    Version: '1.6',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Herta Space Station',
    Height: 'Medium',
    img: '../images/Hsr/Character_Ruan_Mei_Icon.webp'
  },
  {
    id: '40',
    Name: 'Xueyi',
    Path: 'Destruction',
    Element: 'Quantum',
    Version: '"1.6',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Medium',
    img: '../images/Hsr/Character_Xueyi_Icon.webp'
  },
  {
    id: '41',
    Name: 'Black Swan',
    Path: 'Nihility',
    Element: 'Wind',
    Version: '2',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Memetic Entity',
    Worlds: 'Garden of Recollection',
    Height: 'Tall',
    img: '../images/Hsr/Character_Black_Swan_Icon.webp'
  },
  {
    id: '42',
    Name: 'Misha',
    Path: 'Destruction',
    Element: 'Ice',
    Version: '2',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Memetic Entity',
    Worlds: 'Penacony',
    Height: 'Small',
    img: '../images/Hsr/Character_Misha_Icon.webp'
  },
  {
    id: '43',
    Name: 'Sparkle',
    Path: 'Harmony',
    Element: 'Quantum',
    Version: '2',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Masked Fools',
    Height: 'Small',
    img: '../images/Hsr/Character_Sparkle_Icon.webp'
  },
  {
    id: '44',
    Name: 'Acheron',
    Path: 'Nihility',
    Element: 'Lightning',
    Version: '2.1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Oni',
    Worlds: 'Self-Annihilators',
    Height: 'Tall',
    img: '../images/Hsr/Character_Acheron_Icon.webp'
  },
  {
    id: '45',
    Name: 'Aventurine',
    Path: 'Preservation',
    Element: 'Imaginary',
    Version: '2.1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Avgin',
    Worlds: 'Interastral Peace Corporation',
    Height: 'Medium',
    img: '../images/Hsr/Character_Aventurine_Icon.webp'
  },
  {
    id: '46',
    Name: 'Gallagher',
    Path: 'Abundance',
    Element: 'Fire',
    Version: '2.1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Memetic Entity',
    Worlds: 'Penacony',
    Height: 'Tall',
    img: '../images/Hsr/Character_Gallagher_Icon.webp'
  },
  {
    id: '47',
    Name: 'BootHill',
    Path: 'The Hunt',
    Element: 'Physical',
    Version: '2.2',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Galaxy Rangers',
    Height: 'Tall',
    img: '../images/Hsr/Character_Boothill_Icon.webp'
  },
  {
    id: '48',
    Name: 'Robin',
    Path: 'Harmony',
    Element: 'Physical',
    Version: '2.2',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Halovian',
    Worlds: 'Penacony',
    Height: 'Medium',
    img: '../images/Hsr/Character_Robin_Icon.webp'
  },
  {
    id: '49',
    Name: 'Trailblazer (HMC)',
    Path: 'Harmony',
    Element: 'Imaginary',
    Version: '2.2',
    Gender: 'Both',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Artificial Body',
    Worlds: 'Astral Express',
    Height: 'Medium',
    img: '../images/Hsr/Character_Trailblazer_H_Icon.webp'
  },
  {
    id: '50',
    Name: 'Firefly',
    Path: 'Destruction',
    Element: 'Fire',
    Version: '2.3',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Stellarons Hunter',
    Height: 'Medium',
    img: '../images/Hsr/Character_Firefly_Icon.webp'
  },
  {
    id: '51',
    Name: 'Jade',
    Path: 'Erudition',
    Element: 'Quantum',
    Version: '2.3',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Interastral Peace Corporation',
    Height: 'Tall',
    img: '../images/Hsr/Character_Jade_Icon.webp'
  },
  {
    id: '52',
    Name: 'Jiaoqiu',
    Path: 'Nihility',
    Element: 'Fire',
    Version: '2.4',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Foxian',
    Worlds: 'The Xianshou Luofu',
    Height: 'Medium',
    img: '../images/Hsr/Character_Jiaoqiu_Icon.webp'
  },
  {
    id: '53',
    Name: 'March 7th (hunt)',
    Path: 'The Hunt',
    Element: 'Imaginary',
    Version: '2.4',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Astral Express',
    Height: 'Medium',
    img: '../images/Hsr/Character_March_Hunt_Icon.webp'
  },
  {
    id: '54',
    Name: 'Yunli',
    Path: 'Destruction',
    Element: 'Physical',
    Version: '2.4',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Xianzhou Native',
    Worlds: 'The Xianshou Luofu',
    Height: 'Small',
    img: '../images/Hsr/Character_Yunli_Icon.webp'
  },
  {
    id: '55',
    Name: 'Feixiao',
    Path: 'The Hunt',
    Element: 'Wind',
    Version: '2.5',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Foxian',
    Worlds: 'The Xianshou Luofu',
    Height: 'Tall',
    img: '../images/Hsr/Character_Feixiao_Icon.webp'
  },
  {
    id: '56',
    Name: 'Lingsha',
    Path: 'Abundance',
    Element: 'Fire',
    Version: '2.5',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Vidyadhara',
    Worlds: 'The Xianshou Luofu',
    Height: 'Medium',
    img: '../images/Hsr/Character_Lingsha_Icon.webp'
  },
  {
    id: '57',
    Name: 'Moze',
    Path: 'The Hunt',
    Element: 'Lightning',
    Version: '2.5',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'The Xianshou Luofu',
    Height: 'Tall',
    img: '../images/Hsr/Character_Moze_Icon.webp'
  },
  {
    id: '58',
    Name: 'Rappa',
    Path: 'Erudition',
    Element: 'Imaginary',
    Version: '2.6',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Galaxy Rangers',
    Height: 'Medium',
    img: '../images/Hsr/Character_Rappa_Icon.webp'
  },
  {
    id: '59',
    Name: 'Fugue',
    Path: 'Nihility',
    Element: 'Fire',
    Version: '2.7',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Foxian',
    Worlds: 'The Xianshou Luofu',
    Height: 'Medium',
    img: '../images/Hsr/Character_Fugue_Icon.webp'
  },
  {
    id: '60',
    Name: 'Sunday',
    Path: 'Harmony',
    Element: 'Imaginary',
    Version: '2.7',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Halovian',
    Worlds: 'Penacony',
    Height: 'Medium',
    img: '../images/Hsr/Character_Sunday_Icon.webp'
  },
  {
    id: '61',
    Name: 'Aglaea',
    Path: 'Remembrance',
    Element: 'Lightning',
    Version: '3',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Amphoreus',
    Height: 'Tall',
    img: '../images/Hsr/Character_Aglaea_Icon.webp'
  },
  {
    id: '62',
    Name: 'The Herta',
    Path: 'Erudition',
    Element: 'Ice',
    Version: '3',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Herta Space Station',
    Height: 'Medium',
    img: '../images/Hsr/Character_The_Herta_Icon.webp'
  },
  {
    id: '63',
    Name: 'Trailblazer (RMC)',
    Path: 'Remembrance',
    Element: 'Ice',
    Version: '3',
    Gender: 'Both',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Artificial Body',
    Worlds: 'Astral Express',
    Height: 'Medium',
    img: '../images/Hsr/Character_Trailblazer_R_Icon.webp'
  },
  {
    id: '64',
    Name: 'Mydei',
    Path: 'Destruction',
    Element: 'Imaginary',
    Version: '3.1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Amphoreus',
    Height: 'Tall',
    img: '../images/Hsr/Character_Mydei_Icon.webp'
  },
  {
    id: '65',
    Name: 'Tribbie',
    Path: 'Harmony',
    Element: 'Quantum',
    Version: '3.1',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Amphoreus',
    Height: 'Small',
    img: '../images/Hsr/Character_Tribbie_Icon.webp'
  },
  {
    id: '66',
    Name: 'Anaxa',
    Path: 'Erudition',
    Element: 'Wind',
    Version: '3.3',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Amphoreus',
    Height: 'Tall',
    img: '../images/Hsr/Character_Anaxa_Icon.webp'
  },
  {
    id: '67',
    Name: 'Castorice',
    Path: 'Remembrance',
    Element: 'Quantum',
    Version: '3.2',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Amphoreus',
    Height: 'Medium',
    img: '../images/Hsr/Character_Castorice_Icon.webp'
  },
  {
    id: '68',
    Name: 'Cipher',
    Path: 'Nihility',
    Element: 'Quantum',
    Version: '3.3',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Amphoreus',
    Height: 'Medium',
    img: '../images/Hsr/Character_Cipher_Icon.webp'
  },
  {
    id: '69',
    Name: 'Hyacine',
    Path: 'Abundance',
    Element: 'Wind',
    Version: '3.3',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Amphoreus',
    Height: 'Medium',
    img: '../images/Hsr/Character_Hyacine_Icon.webp'
  },
  {
    id: '70',
    Name: 'Phainon',
    Path: 'Destruction',
    Element: 'Physical',
    Version: '3.4',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'Amphoreus',
    Height: 'Tall',
    img: '../images/Hsr/Character_Phainon_Icon.webp'
  },
  {
    id: '71',
    Name: 'Saber',
    Path: 'Destruction',
    Element: 'Wind',
    Version: '3.4',
    Gender: 'Female',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Great Spirit',
    Worlds: 'Penacony',
    Height: 'Medium',
    img: '../images/Hsr/Character_Saber_Icon.webp'
  },
  {
    id: '72',
    Name: 'Archer',
    Path: 'The Hunt',
    Element: 'Quantum',
    Version: '3.4',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Great Spirit',
    Worlds: 'Penacony',
    Height: 'Tall',
    img: '../images/Hsr/Character_Archer_Icon.webp'
  },
  {
    id: '73',
    Name: 'Luocha',
    Path: 'Abundance',
    Element: 'Imaginary',
    Version: '1.1',
    Gender: 'Male',
    Rarity: '✦ ✦ ✦ ✦ ✦',
    Species: 'Human',
    Worlds: 'The Xianshou Luofu',
    Height: 'Tall',
    img: '../images/Hsr/Character_Luocha_Icon.webp'
  }
]