export const persoData = [
    {
        id: 1,
        nom: 'Artoria Pendragon',
        nomKanji: 'アルトリア・ペンドラゴン',
        nb_favorite: 32347,
        seiyuu: 'Ayako Kawasumi',
        age: 35,
        taille: 154,
        genre: 'femme',
        anime_nom: 'Fate',
        img: 'https://cdn.myanimelist.net/images/characters/6/275276.webp',
    },
    {
        id: 2,
        nom: 'Kaori Miyazono',
        nomKanji: '宮園 かをり',
        nb_favorite: 24931,
        seiyuu: 'Risa Taneda',
        age: 15,
        taille: 157,
        genre: 'femme',
        anime_nom: 'Your Lie in April',
        img: 'https://cdn.myanimelist.net/images/characters/14/269375.webp',
    },
    {
        id: 3,
        nom: 'YoRHa No.2 Type B',
        nomKanji: 'ヨルハ2号B型',
        nb_favorite: 2257,
        seiyuu: 'Yui Ishikawa',
        age: 3,
        taille: 168,
        genre: 'femme',
        anime_nom: 'Nier: Automata',
        img: 'https://cdn.myanimelist.net/images/characters/6/489088.webp',
    }
]